# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Ian Muchiri"
email: "ianthegreat254@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: _ixnnn2023
github_username: ianmk7
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)

author:
  name : "Ian Kung'u"
  avatar : "/assets/images/bio-ian.jpg"
  bio    : "I am an aspiring Cybersecurity Professional with a keen interest interest in ethical hacking, threat intelligence, networking and cloud infrastructure."
  links:
    - label: "LinkedIn"
      icon: "fas-fa-fw fa-link"
      url: "https://www.linkedin.com/in/ian-kungu-b67535322/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://ianmk7.github.io/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_ixnnn?igsh=MW0yYTZtZ2I0cjA4NQ=="

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.linkedin.com/in/ian-kungu-b67535322/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://ianmk7.github.io/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_ixnnn?igsh=MW0yYTZtZ2I0cjA4NQ=="

defaults:
 

  - resume_archive:
      path: /resume/
       ## 📄 Resume

### 🎓 Academic Background
- **Microsoft ADC Cybersecurity Skilling Program**, [Cyber Shujaa], [April 2025 - Present]
- **Cybersecurity Training Program**, [Moringa School], [Feb 2024 - Nov 2024]

### 💼 Work Experience
- **IT Support Specialist Intern**, Oasis Outsourcing — *Feb 2025 – Present*
  - Assisting in hardware and software configurations

### 📜 Certifications
- CompTIA Security+ (In Progress)
- Microsoft Certified: Security, Infrastructure and Identity Fundamentals (May 2025)

### 🧠 Skills
- **Tools:** Nmap, Wireshark, Port Swigger
- **Soft Skills:**
- **Team collaboration** – I have actively participated in discussions with my fellow course mates in assignments, class projects and labs on platforms like Port      Swigger and CompTIA course content.
- **Adaptability** – I have adjusted myself to situations as they are by spending more time on the task at hand or working outside of regular hours.
- **Communication** – to keep ourselves updated on tasks to be completed or events that are happening I have used platforms like Mattermost, WhatsApp and Email.
- **Leadership** – I have led discussions in labs and revision sessions with my fellow course mates on the CompTIA course content.

      type: scope
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
